rbacApiVersion: rbac.authorization.k8s.io
namespace: operator-lifecycle-manager
catalog_namespace: operator-lifecycle-manager
operator_namespace: operators
minKubeVersion: 1.11.0
writeStatusName: '""'
imagestream: false
debug: false
installType: upstream
olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 160Mi

catalog:
  replicaCount: 1
  commandArgs: -configmapServerImage=quay.io/operator-framework/configmap-operator-registry@sha256:64b5d2fa9e13fd484f8a9c3b71c5820bdcbb80c1d196fb89297d1f4b063c8e84
  image:
    ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 80Mi

package:
  replicaCount: 2
  image:
    ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 5443
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 50Mi
